name: CI pipeline

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  ci:
    name: CI pipeline
    runs-on: ubuntu-latest

    container:
      image: ubuntu-latest

    services:
      postgres:
        image: postgres:13.5-alpine
        env:
          POSTGRES_DB: rent_your_stuff
          POSTGRES_USER: cuba
          POSTGRES_PASSWORD: cuba
        options: >-
          --health-cm pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Git Checkout
        uses: actions/checkout@v1

      - name: Set Up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run tests
        env:
          MAIN_DATASOURCE_URL: jdbc:postgresql://localhost:5444/rent_your_stuff
          MAIN_DATASOURCE_USERNAME: cuba
          MAIN_DATASOURCE_PASSWORD: cuba
        run: ./gradlew test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() #always run even if the previous step fails
        with:
          report_path: '**/build/test-results/test/TEST-*.xml'
